#!/usr/bin/env python3

import sys
import rospy
import math
import time
from trajectory_msgs.msg import JointTrajectory, JointTrajectoryPoint
from trac_ik_python.trac_ik import IK
from geometry_msgs.msg import PoseStamped

ik_solver = None
pub = None
seed_state = [0.0,-1.5707,1.5707,0.0,1.5707,0.0]

limits_lower = [-1.5, -3.0, 0.0, -1.5, 0.0, -1.5]
limits_upper = [ 4.6,  0.0, 2.5,  1.5, 3.1,  1.5]

def controller_callback(msg):
    global ik_solver, pub, seed_state

    pos = msg.pose.position
    ori = msg.pose.orientation
    ik = ik_solver.get_ik(seed_state, pos.x, pos.y, pos.z, ori.x, ori.y, ori.z, ori.w)

    if ik:
        jt = JointTrajectory()
        jt.joint_names = list(ik_solver.joint_names)

        tp = JointTrajectoryPoint()
        tp.positions = list(ik)
        tp.time_from_start = rospy.Duration(nsecs=500000000)
        jt.points = [tp]

        jt.header.stamp = rospy.Time.now()
        pub.publish(jt)
    else:
        rospy.logwarn("IK_ERROR")

def main():
    global ik_solver, pub
    rospy.init_node('joint_driver', anonymous=True)
    pub = rospy.Publisher('out', JointTrajectory, queue_size=10)
    rospy.Subscriber('in', PoseStamped, controller_callback)

    ik_solver = IK("base_link", "rg2", timeout=0.05, solve_type="Distance")
    ik_solver.set_joint_limits(limits_lower, limits_upper)

    rospy.spin()

if __name__=='__main__':
    try:
        main()
    except rospy.ROSInterruptException:
        pass
